apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "whatsleft.fullname" . }}-view
  labels:
    app.kubernetes.io/name: {{ include "whatsleft.name" . }}-view
    helm.sh/chart: {{ include "whatsleft.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.view.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "whatsleft.name" . }}-view
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "whatsleft.name" . }}-view
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-view
          image: "{{ .Values.view.image.repository }}:{{ .Values.view.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.view.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.view.resources | nindent 12 }}
      {{- with .Values.view.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.view.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.view.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
