# Valores específicos para o Oracle Kubernetes Engine (OKE)


api:
  image:
    # Substitua pelo endereço do seu OCIR (Oracle Container Registry)
    # Exemplo: gru.ocir.io/sua-tenancy/whatsleft-api
    repository: sa-saopaulo-1.ocir.io/gruyvux68qma/whatsleft-api
    tag: "latest"
  service:
    type: ClusterIP # A API fica interna por segurança

view:
  image:
    # Substitua pelo endereço do seu OCIR
    # Exemplo: gru.ocir.io/sua-tenancy/whatsleft-view
    repository: sa-saopaulo-1.ocir.io/gruyvux68qma/whatsleft-view
    tag: "latest"
  service:
    # No Oracle Cloud, usar LoadBalancer vai provisionar automaticamente 
    # um OCI Load Balancer com um IP público para o frontend.
    type: LoadBalancer

# Caso prefira usar Ingress em vez de LoadBalancer direto no frontend
ingress:
  enabled: false
  # annotations:
  #   kubernetes.io/ingress.class: nginx

# Configuração mínima do Elasticsearch para economizar recursos no OKE
elasticsearch:
  master:
    replicaCount: 1
  coordinating:
    replicaCount: 0
  data:
    replicaCount: 0
  ingest:
    replicaCount: 0
  # Aumenta o tempo de tolerância para o pull da imagem caso haja limitação do Docker Hub
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 2Gi

kibana:
  resources:
    requests:
      cpu: "100m"
      memory: "512Mi"
